export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_COUNTRIES_START = 'FETCH_COUNTRIES_START';
export const FETCH_COUNTRIES_SUCCESS = 'FETCH_COUNTRIES_SUCCESS';
export const FETCH_COUNTRIES_FAIL = 'FETCH_COUNTRIES_FAIL';

export const FETCH_FOLLOWING_USERS_START = 'FETCH_FOLLOWING_USERS_START';
export const FETCH_FOLLOWING_USERS_SUCCESS = 'FETCH_FOLLOWING_USERS_SUCCESS';
export const FETCH_FOLLOWING_USERS_FAIL = 'FETCH_FOLLOWING_USERS_FAIL';

export const FETCH_TRAVEL_PLANS_START = 'FETCH_TRAVEL_PLANS_START';
export const FETCH_TRAVEL_PLANS_SUCCESS = 'FETCH_TRAVEL_PLANS_SUCCESS';
export const FETCH_TRAVEL_PLANS_FAIL = 'FETCH_TRAVEL_PLANS_FAIL';
